### ISSUE TITLE
User Story 1: There's a RB Landing Page

### ISSUE THREAD

**Issue by kakoga** [rmesghali/RailsBridgeSD#5]
As a user, I can go to the homepage and get an idea of what RailsBridge is about

**Comment by kakoga** [comment]
I added a Welcome controller and a def index to render Hello World on the home page.
That's as far as I've gotten. Haven't pushed up yet - wanted to work on it a bit more to get the basics done on it. 
Where are you at? I hope we're not doubling up?

**Comment by despino** [comment]
I too have added a Welcome controller. So yes, we are doubling up. I created the landing page, and have added the newsletter feature. I am stuck on one part, but I'll be testing it, and then pushing it up soon.
